name: Build

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # For some reason doing this in pyproject.toml does not seem to work :(
      - name: Set Windows compilation env vars
        shell: bash
        run: |
          set -exo pipefail
          echo "INCLUDE=$GITHUB_WORKSPACE\\liblsl\\include" >> $GITHUB_ENV
          echo "LIB=$GITHUB_WORKSPACE\\liblsl\\build\\Release" >> $GITHUB_ENV
        if: runner.os == 'Windows'
      - uses: pypa/cibuildwheel@v2.21.3
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
